spring.application.name=credit-general-banque-api
spring.datasource.url=jdbc:h2:file:./db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.jpa.hibernate.ddl-auto=update

#Logs
logging.level.root=INFO
logging.level.com.monsite=DEBUG
logging.file.name=logs/app.log
logging.pattern.console=%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n


#Systeme de gestion de mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=apigsbmail@gmail.com
spring.mail.password=odte lcee ilfi ejfn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Spring security
jwt.secret=MaSuperCleUltraSecretePourJWT123456

#Reset la base \u00E0 chaque lancement
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# \u00E0 retirer en production
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
